// src/rateLimitData.js

/**
 * @typedef {Object} RateLimitData
 * @property {string} API
 * @property {string} SubscriptionType
 * @property {string} EndpointType
 * @property {string} Method
 * @property {string} Path
 * @property {string} BurstLimit
 * @property {string} SustainedLimit
 * @property {string} SustainedLimitUnits
 * @property {string} Notes // Now used as Request Type
 * @property {string} Source
 */

/** @type {RateLimitData[]} */
export const rateLimitData = [
  
  // --- ADDED SUBSCRIPTION TIERS FOR DROPDOWN POPULATION ---
  // Using Enterprise data as a template for new tiers per request
  {
    API: "Authentication",
    SubscriptionType: "Free",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/free",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Free tier",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Self Service",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/self-service",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Self Service tier",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Tier Dev Private Cloud",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/dev-cloud",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Tier Dev Private Cloud",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Basic 100 RPS (1x)",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-basic-100",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Basic 100 RPS (1x)",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Performance 500 RPS (5x)",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-perf-500",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Performance 500 RPS (5x)",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Performance 1500 RPS (15x)",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-perf-1500",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Performance 1500 RPS (15x)",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Performance 3000 RPS (30x) and 3000 RPS (30x) Burst",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-perf-3000-burst",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Performance 3000 RPS (30x) and 3000 RPS (30x) Burst",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Performance 6000 RPS (60x) and 6000 RPS (60x) Burst",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-perf-6000-burst",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Performance 6000 RPS (60x) and 6000 RPS (60x) Burst",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Private Cloud Performance 10,000 RPS (100x)",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo/cloud-perf-10000",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Template data for Private Cloud Performance 10,000 RPS (100x)",
    Source: "N/A",
  },
  // --- END ADDED SUBSCRIPTION TIERS ---


  // --- AUTHENTICATION API Limits (SubscriptionType: Enterprise) ---
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "User Info",
    Method: "GET, POST",
    Path: "/userinfo",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Change Password / Reset Password",
    Method: "POST",
    Path: "/dbconnections/change_password",
    BurstLimit: "10",
    SustainedLimit: "1",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address to a unique Email Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Get Passwordless Code or Link",
    Method: "GET, POST",
    Path: "/passwordless/start",
    BurstLimit: "50",
    SustainedLimit: "50",
    SustainedLimitUnits: "per hour",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Native Social Login (Apple / Facebook Only)",
    Method: "POST",
    Path: "/oauth/token", // Assumed endpoint for native social token verification/exchange
    BurstLimit: "50",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "Any Request for Apple or Facebook Native Social Login",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Dynamic Application (Client) Registration",
    Method: "POST",
    Path: "/oauth/client-registration",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per second",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Universal Logout",
    Method: "POST",
    Path: "/logout",
    BurstLimit: "35",
    SustainedLimit: "35",
    SustainedLimitUnits: "per second",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Pushed Authorization Requests (PAR)",
    Method: "POST",
    Path: "/par",
    BurstLimit: "100",
    SustainedLimit: "100",
    SustainedLimitUnits: "per second",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Back-Channel authorize (CIBA)",
    Method: "POST",
    Path: "/device/authorize",
    BurstLimit: "500",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Device code activation (no prompt)",
    Method: "POST",
    Path: "/oauth/token",
    BurstLimit: "30",
    SustainedLimit: "6",
    SustainedLimitUnits: "per second",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Device code authorization",
    Method: "POST",
    Path: "/oauth/device/code",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per second",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "MFA OOB token exchange",
    Method: "POST",
    Path: "/oauth/token",
    BurstLimit: "12",
    SustainedLimit: "12",
    SustainedLimitUnits: "per minute",
    Notes: "To a unique session",
    Source: "N/A",
  },

  // --- MANAGEMENT API Limits (SubscriptionType: Enterprise) ---
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organizations by Name",
    Method: "GET",
    Path: "/api/v2/organizations/name/{name}",
    BurstLimit: "20",
    SustainedLimit: "200",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Organizations",
    Method: "POST, PATCH, DELETE",
    Path: "/api/v2/organizations",
    BurstLimit: "5",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organization Members",
    Method: "GET",
    Path: "/api/v2/organizations/{id}/members",
    BurstLimit: "40",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Organization Members",
    Method: "POST, DELETE",
    Path: "/api/v2/organizations/{id}/members",
    BurstLimit: "20",
    SustainedLimit: "200",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organization invitation",
    Method: "GET",
    Path: "/api/v2/organizations/{id}/invitations/{invitation_id}",
    BurstLimit: "20",
    SustainedLimit: "200",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organization Member Roles",
    Method: "GET",
    Path: "/api/v2/organizations/{id}/members/{user_id}/roles",
    BurstLimit: "20",
    SustainedLimit: "200",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Organization Member Roles",
    Method: "POST, DELETE",
    Path: "/api/v2/organizations/{id}/members/{user_id}/roles",
    BurstLimit: "20",
    SustainedLimit: "200",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organization Connections",
    Method: "GET",
    Path: "/api/v2/organizations/{id}/enabled_connections",
    BurstLimit: "10",
    SustainedLimit: "100",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Organization Connections",
    Method: "POST, PATCH, DELETE",
    Path: "/api/v2/organizations/{id}/enabled_connections",
    BurstLimit: "5",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Custom Domains",
    Method: "POST",
    Path: "/api/v2/custom-domains/{id}/verify",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Status Connection",
    Method: "GET",
    Path: "/api/v2/connections/{id}/status",
    BurstLimit: "100",
    SustainedLimit: "15",
    SustainedLimitUnits: "per second",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Signing Keys",
    Method: "POST",
    Path: "/api/v2/keys/signing",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per day",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Partials for a Prompt",
    Method: "GET",
    Path: "/api/v2/prompts/{prompt}/partials",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Partials for a Prompt",
    Method: "PUT",
    Path: "/api/v2/prompts/{prompt}/partials",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Clients (with query)",
    Method: "GET",
    Path: "/api/v2/clients",
    BurstLimit: "5",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Only applies to the usage of the q parameter.",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read Organization Client Grants",
    Method: "GET",
    Path: "/api/v2/organization-client-grants",
    BurstLimit: "10",
    SustainedLimit: "100",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write Organization Client Grants",
    Method: "POST",
    Path: "/api/v2/organization-client-grants",
    BurstLimit: "5",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write email templates",
    Method: "POST, PATCH, DELETE",
    Path: "/api/v2/email-templates",
    BurstLimit: "10",
    SustainedLimit: "100",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read email templates",
    Method: "GET",
    Path: "/api/v2/email-templates",
    BurstLimit: "15",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Write email provider",
    Method: "POST, PATCH, DELETE",
    Path: "/api/v2/emails/provider",
    BurstLimit: "10",
    SustainedLimit: "100",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "Management",
    SubscriptionType: "Enterprise",
    EndpointType: "Read email provider",
    Method: "GET",
    Path: "/api/v2/emails/provider",
    BurstLimit: "15",
    SustainedLimit: "150",
    SustainedLimitUnits: "per minute",
    Notes: "Any request",
    Source: "N/A",
  },
  
  // --- SCIM Limits (SubscriptionType: Enterprise) ---
  {
    API: "SCIM",
    SubscriptionType: "Enterprise",
    EndpointType: "Single SCIM connection endpoint",
    Method: "Any request",
    Path: "/scim/v2/connections/{connection-id}",
    BurstLimit: "25",
    SustainedLimit: "25",
    SustainedLimitUnits: "per second",
    Notes: "Any request",
    Source: "N/A",
  },
  {
    API: "SCIM",
    SubscriptionType: "Enterprise",
    EndpointType: "Global tenant limit for all SCIM connections",
    Method: "Any request",
    Path: "/scim/v2/connections/*",
    BurstLimit: "100",
    SustainedLimit: "100",
    SustainedLimitUnits: "per second",
    Notes: "Any request",
    Source: "N/A",
  },

  // --- UNIVERSAL LOGIN PROMPT Limits (SubscriptionType: Enterprise) ---
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Universal login prompts (global)",
    Method: "GET, POST",
    Path: "/authorize, /continue, etc.",
    BurstLimit: "500",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Universal login prompts (per prompt GET)",
    Method: "GET",
    Path: "/authorize, /continue, etc.",
    BurstLimit: "20",
    SustainedLimit: "10",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address and state value.",
    Source: "N/A",
  },
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Universal login prompts (per prompt POST)",
    Method: "POST",
    Path: "/authorize, /continue, etc.",
    BurstLimit: "10",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Password reset prompt",
    Method: "GET",
    Path: "/lo/reset",
    BurstLimit: "500",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  // Note: Grouping all MFA/Passwordless prompts as 'Universal Login' limits
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "MFA Push/SMS/Passwordless Prompts (Various)",
    Method: "GET, POST",
    Path: "/mfa/sms, /mfa/push, /passwordless/...",
    BurstLimit: "500",
    SustainedLimit: "500",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Passwordless SMS challenge prompt (POST)",
    Method: "POST",
    Path: "/passwordless/start",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "From an IP Address",
    Source: "N/A",
  },
  {
    API: "Universal Login",
    SubscriptionType: "Enterprise",
    EndpointType: "Device code prompt",
    Method: "GET, POST",
    Path: "/device",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per second",
    Notes: "From an IP Address",
    Source: "N/A",
  },

  // --- FAILURE/MESSAGE Limits (SubscriptionType: Enterprise) ---
  // Note: These are not tied to specific API paths, but to internal rate limiting logic.
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "OTP (6 numeric digits) failures",
    Method: "POST",
    Path: "N/A",
    BurstLimit: "10",
    SustainedLimit: "10",
    SustainedLimitUnits: "per hour",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Recovery code failures",
    Method: "POST",
    Path: "N/A",
    BurstLimit: "10",
    SustainedLimit: "10",
    SustainedLimitUnits: "per hour",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Webauthn challenge failures",
    Method: "N/A",
    Path: "N/A",
    BurstLimit: "15",
    SustainedLimit: "15",
    SustainedLimitUnits: "per minute",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Push notifications sent per user",
    Method: "N/A",
    Path: "N/A",
    BurstLimit: "5",
    SustainedLimit: "5",
    SustainedLimitUnits: "per minute",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "SMS sent per user",
    Method: "N/A",
    Path: "N/A",
    BurstLimit: "10",
    SustainedLimit: "1",
    SustainedLimitUnits: "per hour",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
  {
    API: "Authentication",
    SubscriptionType: "Enterprise",
    EndpointType: "Email sent per user",
    Method: "N/A",
    Path: "N/A",
    BurstLimit: "20",
    SustainedLimit: "1",
    SustainedLimitUnits: "per minute",
    Notes: "To a unique User ID",
    Source: "N/A",
  },
    {
    API: "Authentication",
    SubscriptionType: "Enterprise", // Assumed tier, as it's the dominant tier in your data
    EndpointType: "Email Verification Page/Flow",
    Method: "GET",
    Path: "/u/email-verification",
    BurstLimit: "20",           // Derived from log detail: "limit": {"size": 20, "global": false}
    SustainedLimit: "5",  // Sustained limit is not provided in the log; setting to Unknown
    SustainedLimitUnits: "per minute", // Best guess for a burst of 20. You should confirm this unit.
    Notes: "per IP address",
    Source: "Confirmed via Auth0 log event 'api_limit'",
  },

];
